server:
  port: 8080

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/lifters?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=GMT-3
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true