CREATE TABLE candidato (
	id VARCHAR(36) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	numero INT UNIQUE,
	legenda VARCHAR(50),
	cargo VARCHAR(50) NOT NULL,
	criadoEm DATETIME,
	alteradoEm DATETIME,
	deletadoEm DATETIME,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE cargo (
	id VARCHAR(36) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	criadoEm DATETIME,
	alteradoEm DATETIME,
	deletadoEm DATETIME,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE eleitor (
	id VARCHAR(36) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	cpf INT UNIQUE,
	idCargo VARCHAR(36),
	criadoEm DATETIME,
	alteradoEm DATETIME,
	deletadoEm DATETIME,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;